export const DATA = [
  {
    id: 18,
    genre_id: 4,
    channel_number: 0,
    title: 'SVBC',
    icon_url: 'http://202.62.66.103',
    pin_protected: 'false',
    stream_source_id: 1,
    stream_url: 'http://stream2.citymediaservices.co.in:80/SVBC/index.m3u8',
    channel_mode: 'live',
    stream_format: '2',
    token: 0,
    token_url: 'Token Url',
    encryption: 0,
    encryption_url: 'Encryption url',
    drm_platform: 'none',
    is_octoshape: 0,
    favorite_channel: '0',
  },
  {
    id: 2,
    genre_id: 1,
    channel_number: 2,
    title: 'V6',
    icon_url: 'http://202.62.66.103',
    pin_protected: 'false',
    stream_source_id: 1,
    stream_url: 'http://202.62.66.105:80/V6/index.m3u8',
    channel_mode: 'live',
    stream_format: '3',
    token: 0,
    token_url: 'Token Url',
    encryption: 0,
    encryption_url: 'Encryption url',
    drm_platform: 'none',
    is_octoshape: 0,
    favorite_channel: '0',
  },
  {
    id: 3,
    genre_id: 1,
    channel_number: 3,
    title: 'T NEWS',
    icon_url: 'http://202.62.66.103',
    pin_protected: 'false',
    stream_source_id: 1,
    stream_url: 'http://202.62.66.105:80/TNEWS/index.m3u8',
    channel_mode: 'live',
    stream_format: '3',
    token: 0,
    token_url: 'Token Url',
    encryption: 0,
    encryption_url: 'Encryption url',
    drm_platform: 'none',
    is_octoshape: 0,
    favorite_channel: '0',
  },
  {
    id: 4,
    genre_id: 1,
    channel_number: 4,
    title: 'TV9',
    icon_url: 'http://202.62.66.103',
    pin_protected: 'false',
    stream_source_id: 1,
    stream_url: 'http://202.62.66.100:8080/TV9Telugu/index.m3u8',
    channel_mode: 'live',
    stream_format: '2',
    token: 1,
    token_url: 'Token Url',
    encryption: 0,
    encryption_url: 'Encryption url',
    drm_platform: 'none',
    is_octoshape: 0,
    favorite_channel: '0',
  },
  {
    id: 11,
    genre_id: 1,
    channel_number: 5,
    title: 'NTV',
    icon_url: 'http://202.62.66.103',
    pin_protected: 'false',
    stream_source_id: 1,
    stream_url: 'http://202.62.66.105:80/NTV/index.m3u8',
    channel_mode: 'live',
    stream_format: '3',
    token: 0,
    token_url: 'Token Url',
    encryption: 0,
    encryption_url: 'Encryption url',
    drm_platform: 'none',
    is_octoshape: 0,
    favorite_channel: '0',
  },
  {
    id: 6,
    genre_id: 1,
    channel_number: 6,
    title: 'SAKSHI TV',
    icon_url: 'http://202.62.66.103',
    pin_protected: 'false',
    stream_source_id: 1,
    stream_url: 'http://202.62.66.107:80/SakshiTV/index.m3u8',
    channel_mode: 'live',
    stream_format: '3',
    token: 0,
    token_url: 'Token Url',
    encryption: 0,
    encryption_url: 'Encryption url',
    drm_platform: 'none',
    is_octoshape: 0,
    favorite_channel: '0',
  },
  {
    id: 7,
    genre_id: 1,
    channel_number: 7,
    title: '10 TV',
    icon_url: 'http://202.62.66.103',
    pin_protected: 'false',
    stream_source_id: 1,
    stream_url: 'http://202.62.66.105:80/10TV/index.m3u8',
    channel_mode: 'live',
    stream_format: '2',
    token: 0,
    token_url: 'Token Url',
    encryption: 0,
    encryption_url: 'Encryption url',
    drm_platform: 'none',
    is_octoshape: 0,
    favorite_channel: '0',
  },
  {
    id: 9,
    genre_id: 1,
    channel_number: 8,
    title: 'HMTV',
    icon_url: 'http://202.62.66.103',
    pin_protected: 'false',
    stream_source_id: 1,
    stream_url: 'http://202.62.66.105:80/HMTV/index.m3u8',
    channel_mode: 'live',
    stream_format: '2',
    token: 0,
    token_url: 'Token Url',
    encryption: 0,
    encryption_url: 'Encryption url',
    drm_platform: 'none',
    is_octoshape: 0,
    favorite_channel: '0',
  },
  {
    id: 13,
    genre_id: 1,
    channel_number: 12,
    title: 'CVR NEWS',
    icon_url: 'http://202.62.66.103',
    pin_protected: 'false',
    stream_source_id: 1,
    stream_url: 'http://202.62.66.105:80/CVR_NEWS/index.m3u8',
    channel_mode: 'live',
    stream_format: '2',
    token: 0,
    token_url: 'Token Url',
    encryption: 0,
    encryption_url: 'Encryption url',
    drm_platform: 'none',
    is_octoshape: 0,
    favorite_channel: '0',
  },
  {
    id: 19,
    genre_id: 1,
    channel_number: 15,
    title: '4K ENCODER',
    icon_url: 'http://202.62.66.103',
    pin_protected: 'false',
    stream_source_id: 1,
    stream_url:
      'http://stream1.citymediaservices.co.in:80/ENCODERTEST/index.m3u8',
    channel_mode: 'live',
    stream_format: '2',
    token: 0,
    token_url: 'Token Url',
    encryption: 0,
    encryption_url: 'Encryption url',
    drm_platform: 'none',
    is_octoshape: 0,
    favorite_channel: '0',
  },
  {
    id: 14,
    genre_id: 1,
    channel_number: 26,
    title: 'INDIA AHEAD',
    icon_url: 'http://202.62.66.103',
    pin_protected: 'false',
    stream_source_id: 1,
    stream_url: 'http://202.62.66.105:80/INDIA_AHEAD/index.m3u8',
    channel_mode: 'live',
    stream_format: '2',
    token: 0,
    token_url: 'Token Url',
    encryption: 0,
    encryption_url: 'Encryption url',
    drm_platform: 'none',
    is_octoshape: 0,
    favorite_channel: '0',
  },
  {
    id: 15,
    genre_id: 8,
    channel_number: 102,
    title: 'MASTII',
    icon_url: 'http://202.62.66.103',
    pin_protected: 'false',
    stream_source_id: 1,
    stream_url: 'http://202.62.66.106:80/Mastiii/index.m3u8',
    channel_mode: 'live',
    stream_format: '3',
    token: 0,
    token_url: 'Token Url',
    encryption: 0,
    encryption_url: 'Encryption url',
    drm_platform: 'none',
    is_octoshape: 0,
    favorite_channel: '0',
  },
  {
    id: 7,
    genre_id: 1,
    channel_number: 7,
    title: '10 TV',
    icon_url: 'http://202.62.66.103',
    pin_protected: 'false',
    stream_source_id: 1,
    stream_url: 'http://202.62.66.105:80/10TV/index.m3u8',
    channel_mode: 'live',
    stream_format: '2',
    token: 0,
    token_url: 'Token Url',
    encryption: 0,
    encryption_url: 'Encryption url',
    drm_platform: 'none',
    is_octoshape: 0,
    favorite_channel: '0',
  },
  {
    id: 9,
    genre_id: 1,
    channel_number: 8,
    title: 'HMTV',
    icon_url: 'http://202.62.66.103',
    pin_protected: 'false',
    stream_source_id: 1,
    stream_url: 'http://202.62.66.105:80/HMTV/index.m3u8',
    channel_mode: 'live',
    stream_format: '2',
    token: 0,
    token_url: 'Token Url',
    encryption: 0,
    encryption_url: 'Encryption url',
    drm_platform: 'none',
    is_octoshape: 0,
    favorite_channel: '0',
  },
  {
    id: 13,
    genre_id: 1,
    channel_number: 12,
    title: 'CVR NEWS',
    icon_url: 'http://202.62.66.103',
    pin_protected: 'false',
    stream_source_id: 1,
    stream_url: 'http://202.62.66.105:80/CVR_NEWS/index.m3u8',
    channel_mode: 'live',
    stream_format: '2',
    token: 0,
    token_url: 'Token Url',
    encryption: 0,
    encryption_url: 'Encryption url',
    drm_platform: 'none',
    is_octoshape: 0,
    favorite_channel: '0',
  },
  {
    id: 19,
    genre_id: 1,
    channel_number: 15,
    title: '4K ENCODER',
    icon_url: 'http://202.62.66.103',
    pin_protected: 'false',
    stream_source_id: 1,
    stream_url:
      'http://stream1.citymediaservices.co.in:80/ENCODERTEST/index.m3u8',
    channel_mode: 'live',
    stream_format: '2',
    token: 0,
    token_url: 'Token Url',
    encryption: 0,
    encryption_url: 'Encryption url',
    drm_platform: 'none',
    is_octoshape: 0,
    favorite_channel: '0',
  },
  {
    id: 14,
    genre_id: 1,
    channel_number: 26,
    title: 'INDIA AHEAD',
    icon_url: 'http://202.62.66.103',
    pin_protected: 'false',
    stream_source_id: 1,
    stream_url: 'http://202.62.66.105:80/INDIA_AHEAD/index.m3u8',
    channel_mode: 'live',
    stream_format: '2',
    token: 0,
    token_url: 'Token Url',
    encryption: 0,
    encryption_url: 'Encryption url',
    drm_platform: 'none',
    is_octoshape: 0,
    favorite_channel: '0',
  },
  {
    id: 15,
    genre_id: 8,
    channel_number: 102,
    title: 'MASTII',
    icon_url: 'http://202.62.66.103',
    pin_protected: 'false',
    stream_source_id: 1,
    stream_url: 'http://202.62.66.106:80/Mastiii/index.m3u8',
    channel_mode: 'live',
    stream_format: '3',
    token: 0,
    token_url: 'Token Url',
    encryption: 0,
    encryption_url: 'Encryption url',
    drm_platform: 'none',
    is_octoshape: 0,
    favorite_channel: '0',
  },
];
